language: cpp
dist: xenial
sudo: false

# Only build master branch, other branches will have a Pull Request build.
branches:
  only:
    - master

matrix:
  include:
    - os: linux
      compiler: gcc-4.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
            - libglu1-mesa-dev
            - libxxf86vm-dev
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - libx11-dev
            - cmake
      script:
        - cmake --version
        - cmake
        - make -j 2
    - os: osx
      compiler: clang
      script:
        - cmake --version
        - cmake
        - make -j 2
